create table if not exists users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar(255) NOT NULL,
    email varchar(512) UNIQUE NOT NULL
);

create table if not exists requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(512) NOT NULL,
    requester_id bigint NOT NULL,
    created_date timestamp without time zone NOT NULL
);

create table if not exists offers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id bigint NOT NULL,
    requester_id bigint NOT NULL,
    item_id bigint NOT NULL

);

create table if not exists items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    is_available boolean NOT NULL,
    owner_id bigint,
    request_id bigint
);

create table if not exists bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    item_id bigint,
    booker_id bigint,
    status varchar(12)
);

create table if not exists comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(512) NOT NULL,
    item_id bigint,
    author_id bigint,
    created_date timestamp without time zone NOT NULL
);

alter TABLE items
    drop CONSTRAINT IF EXISTS fk_items_to_users;

alter TABLE items
    ADD CONSTRAINT fk_items_to_users FOREIGN KEY (owner_id) REFERENCES users (id)
        ON delete CASCADE ON update CASCADE;

alter TABLE bookings
    drop CONSTRAINT IF EXISTS fk_bookings_to_items;

alter TABLE bookings
    ADD CONSTRAINT fk_bookings_to_items FOREIGN KEY (item_id) REFERENCES items (id)
        ON delete CASCADE ON update CASCADE;


alter TABLE bookings
    drop CONSTRAINT IF EXISTS fk_bookings_to_users;

alter TABLE bookings
    ADD CONSTRAINT fk_bookings_to_users FOREIGN KEY (booker_id) REFERENCES users (id)
        ON delete CASCADE ON update CASCADE;


alter TABLE comments
    drop CONSTRAINT IF EXISTS fk_comments_to_items;

alter TABLE comments
    ADD CONSTRAINT fk_comments_to_items FOREIGN KEY (item_id) REFERENCES items (id)
        ON delete CASCADE ON update CASCADE;


alter TABLE comments
    drop CONSTRAINT IF EXISTS fk_comments_to_users;

alter TABLE comments
    ADD CONSTRAINT fk_comments_to_users FOREIGN KEY (author_id) REFERENCES users (id)
        ON delete CASCADE ON update CASCADE;


alter TABLE requests
    drop CONSTRAINT IF EXISTS fk_request_to_users;

alter TABLE requests
    ADD CONSTRAINT fk_request_to_users FOREIGN KEY (requester_id) REFERENCES users (id)
        ON delete CASCADE ON update CASCADE;

alter TABLE offers
    drop CONSTRAINT IF EXISTS fk_item_offer_to_request;

alter TABLE offers
    ADD CONSTRAINT fk_item_offer_to_request FOREIGN KEY (request_id) REFERENCES requests (id)
        ON delete CASCADE ON update CASCADE;