drop TABLE IF EXISTS users,items,bookings,request,comments;

create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS identity NOT NULL,
  name varchar(255) NOT NULL,
  email varchar(512) NOT NULL UNIQUE,
  CONSTRAINT pk_user PRIMARY KEY (id)
);

create TABLE items (
  id bigint generated BY DEFAULT AS identity (maxvalue 2147483647) CONSTRAINT items_pk PRIMARY KEY,
  name varchar(100) NOT NULL,
  description varchar(512) NOT NULL,
  available boolean NOT NULL,
  owner_id bigint NOT NULL CONSTRAINT items_users_id_fk REFERENCES users,
  request_id bigint
);

create TABLE bookings (
    id bigint GENERATED BY DEFAULT AS identity NOT NULL,
    start_date timestamp WITHOUT TIME ZONE NOT NULL,
    end_date timestamp WITHOUT TIME ZONE NOT NULL,
    item_id bigint NOT NULL CONSTRAINT bookings_items_id_fk REFERENCES items,
    booker_id bigint NOT NULL CONSTRAINT bookings_users_id_fk REFERENCES users,
    status bigint NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);


create TABLE request (
    id bigint GENERATED BY DEFAULT AS identity NOT NULL,
    description varchar(512) NOT NULL,
    requester_id bigint NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

create TABLE comments (
    id bigint GENERATED BY DEFAULT AS identity NOT NULL,
    text varchar(512) NOT NULL,
    item_id bigint NOT NULL CONSTRAINT comments_items_id_fk REFERENCES items,
    author_id bigint NOT NULL CONSTRAINT comments_users_id_fk REFERENCES users,
    created timestamp WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);